import os, re, csv, json

BASE = os.path.dirname(os.path.abspath(__file__))
IMAGES = os.path.join(BASE, "images")
GUIDE = os.path.join(BASE, "guide")


def natkey(s):
    return [int(p) if p.isdigit() else p for p in re.split(r'(\d+)', s.lower())]


# Branding / non-emotion images to skip (case-insensitive filename match)
EXCLUDE = {"ea globe last post.png"}

# Emotions where the standalone title card sorts first but should NOT be the cover.
# The named card (lowercased) is moved to the end so image "001" becomes the cover.
DEMOTE = {"AMBITIOUS": "ambition.png", "INTERESTING": "interest.png"}


emotions = []
with open(os.path.join(BASE, "data.csv"), newline='', encoding='utf-8') as f:
    for row in csv.DictReader(f):
        folder = row['image_folder'].strip()
        fp = os.path.join(IMAGES, folder)
        imgs = [fn for fn in os.listdir(fp)
                if os.path.isfile(os.path.join(fp, fn)) and fn.lower().endswith('.png')
                and fn.lower() not in EXCLUDE] if os.path.isdir(fp) else []
        imgs.sort(key=natkey)
        # Demote a standalone title card so image "001" becomes the cover.
        card = DEMOTE.get(folder.upper())
        if card:
            moved = [fn for fn in imgs if fn.lower() == card]
            imgs = [fn for fn in imgs if fn.lower() != card] + moved
        emotions.append({
            "name": row['emotion_name'].strip(),
            "folder": folder,
            "description": row['short_description'].strip(),
            "connected": [c.strip() for c in row['connected_emotions'].split(';') if c.strip()],
            "cover": imgs[0] if imgs else None,
            "images": imgs,
        })

valid = {e['folder'].upper(): e['folder'] for e in emotions}
valid_names = {e['name'].upper(): e['folder'] for e in emotions}
for e in emotions:
    e['connectedResolved'] = [
        {"label": c, "folder": valid.get(c.upper()) or valid_names.get(c.upper())}
        for c in e['connected']
    ]

guides = [{"file": fn, "title": os.path.splitext(fn)[0]}
          for fn in sorted(os.listdir(GUIDE)) if fn.lower().endswith('.pdf')] if os.path.isdir(GUIDE) else []

data = {"emotions": emotions, "guides": guides, "guideDir": "guide"}

# JSON copy (used when the site is served over http/https)
with open(os.path.join(BASE, "manifest.json"), 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

# Embedded JS copy (lets the site work with NO server — even by double-clicking index.html)
os.makedirs(os.path.join(BASE, "assets"), exist_ok=True)
with open(os.path.join(BASE, "assets", "data.js"), 'w', encoding='utf-8') as f:
    f.write("/* Auto-generated by generate_manifest.py - do not edit by hand. */\n")
    f.write("window.EMOTION_DATA = ")
    json.dump(data, f, ensure_ascii=False)
    f.write(";\n")

print("Wrote manifest.json + assets/data.js:", len(emotions), "emotions,", len(guides), "guides")
